# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_ID             := 00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_TYPE           := base
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_BASE_LAYER     := 
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_SOURCE_INCLUDE := 
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_SOURCE_EXCLUDE := 
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_CACHE_KEY_FILE := .buildcache/cache-keys/base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3
LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_ARCHIVE_FILE   := .buildcache/archives/00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_ID),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_TYPE),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_BASE_LAYER),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_SOURCE_INCLUDE),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_SOURCE_EXCLUDE),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_CACHE_KEY_FILE),$(LAYER_00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3_ARCHIVE_FILE)))

LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_ID             := 01-install-go-6ead8440d181605ee9c56300e887068d085ba102
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_TYPE           := install-go
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_BASE_LAYER     := 00-base-36f009b1b46f02370dfb42b19ed6156a52a7f5c3
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_SOURCE_INCLUDE := 
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_SOURCE_EXCLUDE := 
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-6ead8440d181605ee9c56300e887068d085ba102
LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_ARCHIVE_FILE   := .buildcache/archives/01-install-go-6ead8440d181605ee9c56300e887068d085ba102.tar.gz
$(eval $(call LAYER,$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_ID),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_TYPE),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_BASE_LAYER),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_SOURCE_INCLUDE),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_SOURCE_EXCLUDE),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_CACHE_KEY_FILE),$(LAYER_01-install-go-6ead8440d181605ee9c56300e887068d085ba102_ARCHIVE_FILE)))

LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ID             := 02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_TYPE           := install-go-tools
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_BASE_LAYER     := 01-install-go-6ead8440d181605ee9c56300e887068d085ba102
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_INCLUDE := 
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_EXCLUDE := 
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ARCHIVE_FILE   := .buildcache/archives/02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc.tar.gz
$(eval $(call LAYER,$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ID),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_TYPE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_BASE_LAYER),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_INCLUDE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_EXCLUDE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_CACHE_KEY_FILE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ARCHIVE_FILE)))

LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_ID             := 03-set-workdir-c5be062002c2f7353a51633272712da6a3921778
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_TYPE           := set-workdir
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_BASE_LAYER     := 02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_SOURCE_INCLUDE := 
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_SOURCE_EXCLUDE := 
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_CACHE_KEY_FILE := .buildcache/cache-keys/set-workdir-c5be062002c2f7353a51633272712da6a3921778
LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_ARCHIVE_FILE   := .buildcache/archives/03-set-workdir-c5be062002c2f7353a51633272712da6a3921778.tar.gz
$(eval $(call LAYER,$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_ID),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_TYPE),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_BASE_LAYER),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_SOURCE_INCLUDE),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_SOURCE_EXCLUDE),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_CACHE_KEY_FILE),$(LAYER_03-set-workdir-c5be062002c2f7353a51633272712da6a3921778_ARCHIVE_FILE)))

LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_ID             := 04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_TYPE           := install-yarn
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_BASE_LAYER     := 03-set-workdir-c5be062002c2f7353a51633272712da6a3921778
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_SOURCE_INCLUDE := 
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_SOURCE_EXCLUDE := 
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_CACHE_KEY_FILE := .buildcache/cache-keys/install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5
LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_ARCHIVE_FILE   := .buildcache/archives/04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5.tar.gz
$(eval $(call LAYER,$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_ID),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_TYPE),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_BASE_LAYER),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_SOURCE_INCLUDE),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_SOURCE_EXCLUDE),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_CACHE_KEY_FILE),$(LAYER_04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5_ARCHIVE_FILE)))

LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_ID             := 05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_TYPE           := ui-dependencies
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_BASE_LAYER     := 04-install-yarn-2924ca2287eec8fe0c29c98a3547069f7ef7d1d5
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_SOURCE_INCLUDE := ui/package.json ui/yarn.lock
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_SOURCE_EXCLUDE := 
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_CACHE_KEY_FILE := .buildcache/cache-keys/ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83
LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_ARCHIVE_FILE   := .buildcache/archives/05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83.tar.gz
$(eval $(call LAYER,$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_ID),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_TYPE),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_BASE_LAYER),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_SOURCE_INCLUDE),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_SOURCE_EXCLUDE),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_CACHE_KEY_FILE),$(LAYER_05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83_ARCHIVE_FILE)))

LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_ID             := 06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_TYPE           := build-ui
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_BASE_LAYER     := 05-ui-dependencies-f7572cf365fa287729ae3dbd838d54c1d4a4ad83
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_SOURCE_INCLUDE := ui/
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_SOURCE_EXCLUDE := 
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_CACHE_KEY_FILE := .buildcache/cache-keys/build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4
LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_ARCHIVE_FILE   := .buildcache/archives/06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4.tar.gz
$(eval $(call LAYER,$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_ID),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_TYPE),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_BASE_LAYER),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_SOURCE_INCLUDE),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_SOURCE_EXCLUDE),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_CACHE_KEY_FILE),$(LAYER_06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4_ARCHIVE_FILE)))

LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ID             := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_TYPE           := build-static-assets
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_BASE_LAYER     := 06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_INCLUDE := Makefile
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_EXCLUDE := 
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_CACHE_KEY_FILE := .buildcache/cache-keys/build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ARCHIVE_FILE   := .buildcache/archives/07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59.tar.gz
$(eval $(call LAYER,$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ID),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_TYPE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_BASE_LAYER),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_INCLUDE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_EXCLUDE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_CACHE_KEY_FILE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_ID             := 08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7
LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_ID),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_TYPE),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ID             := 08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ID),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_TYPE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ID             := 08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ID),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_TYPE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ID             := 08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ID),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_TYPE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_ID             := 08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d
LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_ID),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_TYPE),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_ID             := 08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4
LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_ID),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_ID             := 08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd
LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_ID),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_TYPE),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_ID             := 08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1
LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_ID),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_TYPE),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_ID             := 08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e
LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_ID),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_TYPE),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_ID             := 08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0
LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_ID),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_TYPE),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ID             := 08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ID),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_ID             := 08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5
LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_ID),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_TYPE),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ID             := 08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ID),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_TYPE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_ID             := 08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2
LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_ID),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_TYPE),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_ID             := 08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba
LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_ID),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_TYPE),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ID             := 08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ID),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_TYPE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ARCHIVE_FILE)))

LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_ID             := 09-copy-source-020c795efeac45ae1c868131a87666087063bb14
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_TYPE           := copy-source
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_BASE_LAYER     := 08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_SOURCE_INCLUDE := .
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-020c795efeac45ae1c868131a87666087063bb14
LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-020c795efeac45ae1c868131a87666087063bb14.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_ID),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_TYPE),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_BASE_LAYER),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_SOURCE_INCLUDE),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_SOURCE_EXCLUDE),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_CACHE_KEY_FILE),$(LAYER_09-copy-source-020c795efeac45ae1c868131a87666087063bb14_ARCHIVE_FILE)))

LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ID             := 09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_TYPE           := copy-source
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_BASE_LAYER     := 08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_INCLUDE := .
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ID),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_TYPE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_BASE_LAYER),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_INCLUDE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_EXCLUDE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_CACHE_KEY_FILE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ARCHIVE_FILE)))

LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_ID             := 09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_TYPE           := copy-source
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_BASE_LAYER     := 08-warm-go-build-vendor-cache-8f45f536d99f723b911b9d19098ae0b6004b87b1
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_SOURCE_INCLUDE := .
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e
LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_ID),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_TYPE),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_BASE_LAYER),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_SOURCE_INCLUDE),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_SOURCE_EXCLUDE),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_CACHE_KEY_FILE),$(LAYER_09-copy-source-11b0b277f5157870c3444cfbf3d3d54cc5730c6e_ARCHIVE_FILE)))

LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ID             := 09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_TYPE           := copy-source
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_BASE_LAYER     := 08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_INCLUDE := .
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ID),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_TYPE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_BASE_LAYER),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_INCLUDE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_EXCLUDE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_CACHE_KEY_FILE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ARCHIVE_FILE)))

LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_ID             := 09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_TYPE           := copy-source
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_BASE_LAYER     := 08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_SOURCE_INCLUDE := .
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc
LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_ID),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_TYPE),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_BASE_LAYER),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_SOURCE_INCLUDE),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_SOURCE_EXCLUDE),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_CACHE_KEY_FILE),$(LAYER_09-copy-source-4c108464b1e4a4f8c981531932e83baf8db6bbfc_ARCHIVE_FILE)))

LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ID             := 09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_TYPE           := copy-source
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_BASE_LAYER     := 08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_INCLUDE := .
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ID),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_TYPE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_BASE_LAYER),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_INCLUDE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_EXCLUDE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_CACHE_KEY_FILE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ARCHIVE_FILE)))

LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ID             := 09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_TYPE           := copy-source
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_BASE_LAYER     := 08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_INCLUDE := .
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ID),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_TYPE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_BASE_LAYER),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_INCLUDE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_EXCLUDE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_CACHE_KEY_FILE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ARCHIVE_FILE)))

LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_ID             := 09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_TYPE           := copy-source
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_BASE_LAYER     := 08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_SOURCE_INCLUDE := .
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665
LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_ID),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_TYPE),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_BASE_LAYER),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_SOURCE_INCLUDE),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_SOURCE_EXCLUDE),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_CACHE_KEY_FILE),$(LAYER_09-copy-source-92a2a92bd3e67ef7472f5c8d3517dd0266f38665_ARCHIVE_FILE)))

LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_ID             := 09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_TYPE           := copy-source
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_BASE_LAYER     := 08-warm-go-build-vendor-cache-e8885176b9418169deb6580d1af33bfaa756e3ba
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_SOURCE_INCLUDE := .
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-9904cad43a7696e22882e225ab21ce547f231ca2
LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_ID),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_TYPE),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_BASE_LAYER),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_SOURCE_INCLUDE),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_SOURCE_EXCLUDE),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_CACHE_KEY_FILE),$(LAYER_09-copy-source-9904cad43a7696e22882e225ab21ce547f231ca2_ARCHIVE_FILE)))

LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ID             := 09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_TYPE           := copy-source
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_BASE_LAYER     := 08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_INCLUDE := .
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ID),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_TYPE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_BASE_LAYER),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_INCLUDE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_EXCLUDE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_CACHE_KEY_FILE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ARCHIVE_FILE)))

LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_ID             := 09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_TYPE           := copy-source
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_BASE_LAYER     := 08-warm-go-build-vendor-cache-0064f335e9f77809d4308220f82f61bc47173ac7
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_SOURCE_INCLUDE := .
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ba872dc84b8f628f777008f259d8931e87f08f57
LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_ID),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_TYPE),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_BASE_LAYER),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_SOURCE_INCLUDE),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_CACHE_KEY_FILE),$(LAYER_09-copy-source-ba872dc84b8f628f777008f259d8931e87f08f57_ARCHIVE_FILE)))

LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_ID             := 09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_TYPE           := copy-source
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_BASE_LAYER     := 08-warm-go-build-vendor-cache-ba7026485cd7b9d3d58c59e8e807aa89018aa8b5
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_SOURCE_INCLUDE := .
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-c53a56931108bd328afa374ddba2515f05dd652e
LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_ID),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_TYPE),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_BASE_LAYER),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_SOURCE_INCLUDE),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_SOURCE_EXCLUDE),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_CACHE_KEY_FILE),$(LAYER_09-copy-source-c53a56931108bd328afa374ddba2515f05dd652e_ARCHIVE_FILE)))

LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_ID             := 09-copy-source-d43490496eaff11363bd07848504cef97317b363
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_TYPE           := copy-source
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_BASE_LAYER     := 08-warm-go-build-vendor-cache-5effee4fdf8ef3ae9c1e32e0e2975c86bd09936d
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_SOURCE_INCLUDE := .
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-d43490496eaff11363bd07848504cef97317b363
LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-d43490496eaff11363bd07848504cef97317b363.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_ID),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_TYPE),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_BASE_LAYER),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_SOURCE_INCLUDE),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_SOURCE_EXCLUDE),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_CACHE_KEY_FILE),$(LAYER_09-copy-source-d43490496eaff11363bd07848504cef97317b363_ARCHIVE_FILE)))

LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ID             := 09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_TYPE           := copy-source
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_BASE_LAYER     := 08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_INCLUDE := .
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ID),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_TYPE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_BASE_LAYER),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_INCLUDE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_CACHE_KEY_FILE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ARCHIVE_FILE)))

LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_ID             := 09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_TYPE           := copy-source
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_BASE_LAYER     := 08-warm-go-build-vendor-cache-7d53bea16c391c795ae559e210b9d5dd3982b5dd
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_SOURCE_INCLUDE := .
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-f28438f494ace3c68f1f60085c60aa139c766677
LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_ID),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_TYPE),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_BASE_LAYER),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_SOURCE_INCLUDE),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_SOURCE_EXCLUDE),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_CACHE_KEY_FILE),$(LAYER_09-copy-source-f28438f494ace3c68f1f60085c60aa139c766677_ARCHIVE_FILE)))

LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ID             := 09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_TYPE           := copy-source
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_BASE_LAYER     := 08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_INCLUDE := .
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ID),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_TYPE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_BASE_LAYER),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_INCLUDE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_EXCLUDE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_CACHE_KEY_FILE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ARCHIVE_FILE)))
