# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ID             := 02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_TYPE           := install-go-tools
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_BASE_LAYER     := 01-install-go-6ead8440d181605ee9c56300e887068d085ba102
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_INCLUDE := 
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_EXCLUDE := 
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc
LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ARCHIVE_FILE   := .buildcache/archives/02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc.tar.gz
$(eval $(call LAYER,$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ID),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_TYPE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_BASE_LAYER),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_INCLUDE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_SOURCE_EXCLUDE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_CACHE_KEY_FILE),$(LAYER_02-install-go-tools-8d9e08b9a8b96f566137b8ca24c8030c2c191ebc_ARCHIVE_FILE)))
