# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ID             := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_TYPE           := build-static-assets
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_BASE_LAYER     := 06-build-ui-cc32d978ba63215f35a4cc6d199750e6134a51a4
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_INCLUDE := Makefile
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_EXCLUDE := 
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_CACHE_KEY_FILE := .buildcache/cache-keys/build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ARCHIVE_FILE   := .buildcache/archives/07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59.tar.gz
$(eval $(call LAYER,$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ID),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_TYPE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_BASE_LAYER),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_INCLUDE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_SOURCE_EXCLUDE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_CACHE_KEY_FILE),$(LAYER_07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59_ARCHIVE_FILE)))
