# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ID             := 08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb
LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ID),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_TYPE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-f93842ba2fbff4619d233a42b61b97394c6bb3cb_ARCHIVE_FILE)))
