# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ID             := 08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ID),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4_ARCHIVE_FILE)))
