# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ID             := 08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0
LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ID),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_TYPE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-2f7236c51939355aa259ba3b7ec287e10a2c19f0_ARCHIVE_FILE)))
