# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ID             := 08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad
LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ID),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_TYPE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-173739c0dd81bfc3f9d12060219df84d6e6128ad_ARCHIVE_FILE)))
