# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ID             := 08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ID),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_TYPE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e_ARCHIVE_FILE)))
