# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ID             := 08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_BASE_LAYER     := 07-build-static-assets-8a6a39479ac2b0a68efc1116cc309ab4ebf44f59
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ID),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_TYPE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb_ARCHIVE_FILE)))
