# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ID             := 09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_TYPE           := copy-source
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_BASE_LAYER     := 08-warm-go-build-vendor-cache-17e100f02fa578a8f0fffff408c6fadd2a1a27fb
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_INCLUDE := .
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee
LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ID),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_TYPE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_BASE_LAYER),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_INCLUDE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_SOURCE_EXCLUDE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_CACHE_KEY_FILE),$(LAYER_09-copy-source-0f79408e7f86dfe80c68daf69f1d16d16f1b27ee_ARCHIVE_FILE)))
