# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ID             := 09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_TYPE           := copy-source
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_BASE_LAYER     := 08-warm-go-build-vendor-cache-7a6701446ad62d5c8ba98cc56a7235df82990cc4
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_INCLUDE := .
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc
LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ID),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_TYPE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_BASE_LAYER),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_INCLUDE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_SOURCE_EXCLUDE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_CACHE_KEY_FILE),$(LAYER_09-copy-source-44e91311bbacaffb1267b8a5abb6f479a1d130bc_ARCHIVE_FILE)))
