# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ID             := 09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_TYPE           := copy-source
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_BASE_LAYER     := 08-warm-go-build-vendor-cache-d41d6bfb9f3d473bf4dc1f1d1b8530407f1782a2
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_INCLUDE := .
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd
LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ID),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_TYPE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_BASE_LAYER),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_INCLUDE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_SOURCE_EXCLUDE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_CACHE_KEY_FILE),$(LAYER_09-copy-source-fa3fbf42c80603e13ad007f1730f93d074de6fbd_ARCHIVE_FILE)))
