# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ID             := 09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_TYPE           := copy-source
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_BASE_LAYER     := 08-warm-go-build-vendor-cache-a2e19bac2fc07bf23c697f2d0a3a7cdd3d3e4cf0
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_INCLUDE := .
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317
LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ID),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_TYPE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_BASE_LAYER),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_INCLUDE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_SOURCE_EXCLUDE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_CACHE_KEY_FILE),$(LAYER_09-copy-source-b48b25b86f085fd7173562f2a1e0dbd0562ce317_ARCHIVE_FILE)))
