# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ID             := 09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_TYPE           := copy-source
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_BASE_LAYER     := 08-warm-go-build-vendor-cache-99ee811109e8fd69320b800e34dd6be421e1267e
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_INCLUDE := .
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c
LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ID),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_TYPE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_BASE_LAYER),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_INCLUDE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_SOURCE_EXCLUDE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_CACHE_KEY_FILE),$(LAYER_09-copy-source-78a0f07ca37654f020eb057dc5d3d790da04fc3c_ARCHIVE_FILE)))
