# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ID             := 09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_TYPE           := copy-source
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_BASE_LAYER     := 08-warm-go-build-vendor-cache-ce0827c5dfb61d687df88c30441ea52aaba0c86e
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_INCLUDE := .
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced
LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ID),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_TYPE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_BASE_LAYER),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_INCLUDE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_SOURCE_EXCLUDE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_CACHE_KEY_FILE),$(LAYER_09-copy-source-7f9f65d96cfaeec0d7e3a9a73e28ecea25088ced_ARCHIVE_FILE)))
