# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.

LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ID             := 09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_TYPE           := copy-source
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_BASE_LAYER     := 08-warm-go-build-vendor-cache-b54f47022408cac8c1b2db8fd96e541421cfe1c4
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_INCLUDE := .
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92
LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ID),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_TYPE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_BASE_LAYER),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_INCLUDE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_CACHE_KEY_FILE),$(LAYER_09-copy-source-ed7b4907a7a48d643bac8c54afc2537334d6ba92_ARCHIVE_FILE)))
